version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - |
        STS="$( \
          aws sts assume-role \
          --role-arn "${STEP_ASSUME_ROLE_ARN}" \
          --role-session-name "${CODEBUILD_INITIATOR#*/}-${CODEBUILD_BUILD_NUMBER}" \
          --query "Credentials" \
          )"
      - export AWS_ACCESS_KEY_ID="$(jq -r '.AccessKeyId' <<<"${STS}")"
      - export AWS_SECRET_ACCESS_KEY="$(jq -r '.SecretAccessKey' <<<"${STS}")"
      - export AWS_SESSION_TOKEN="$(jq -r '.SessionToken' <<<"${STS}")"
  build:
    commands:
      - make fmt-check
      - make validate
      - make test

